// queuehaven-ui/src/views/LandingComponent/LandingComponent.jsx
import React from 'react';
import {connect} from 'react-redux';
import classNames from 'classnames';
import withStyles from '@material-ui/core/styles/withStyles';

import CalendarComponent from 'views/LandingComponent/CalendarComponent.jsx';
import Footer from 'components/Footer/Footer.jsx';
import GridContainer from 'components/Grid/GridContainer.jsx';
import GridItem from 'components/Grid/GridItem.jsx';
import QueueHavenHeader from 'components/Header/QueueHavenHeader.jsx';
import Parallax from 'components/Parallax/Parallax.jsx';

import landingStyle from 'assets/jss/material-kit-react/views/landingComponent.jsx';

/**
 * Takes the entire application state and returns only the subset of data this component needs.
 * mapStateToProps is called each time the Redux state changes.
 */
function mapStateToProps(state) {
    return {
        user: state.user
    };
};

class LandingComponent extends React.Component {

    render() {
        const {classes} = this.props;

        return (
            <div>
                <QueueHavenHeader/>
                <Parallax filter image={require('assets/img/bg1.png')}
                          className={(this.props.user !== '' ? classes.short : '')}>
                    <div className={classes.container}>
                        {
                            this.props.user === '' ?
                                <GridContainer>
                                    <GridItem xs={12} sm={12} md={12}>
                                        <div>
                                            <img className={classes.center}
                                                 src={require('assets/img/queuehaven-logo.png')} alt=''/>
                                            <h3 className={classes.title}>
                                                Step into the cutting edge world of queue management.
                                            </h3>
                                        </div>
                                    </GridItem>
                                </GridContainer> :
                                null
                        }
                    </div>
                </Parallax>
                <div className={classNames(classes.main, classes.mainRaised)}>
                    {
                        this.props.user !== '' ?
                            <CalendarComponent/> :
                            null
                    }
                </div>
                <Footer/>
            </div>
        );
    }
}

const StatefulLandingComponent = connect(mapStateToProps, null)(LandingComponent)
export default withStyles(landingStyle)(StatefulLandingComponent);

// queuehaven-ui/src/app/components/landing.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-landing',
    templateUrl: './landing.component.html',
    styles: [ ]
})
export class LandingComponent implements OnInit {
    
    constructor() { }

    ngOnInit() {
        
    }

}

<div class="wrapper">
    <div class="page-header section-dark" style="background-image: url('assets/img/bg.png')">
        <div class="filter"></div>
        <div class="content-center">
            <div class="container">
                <div class="title-brand">
                    <img src="assets/img/queuehaven-logo.png" alt="">
                </div>

                <h2 class="presentation-subtitle text-center">Put down the pen and paper and step into the cutting edge world of queue management.</h2>
            </div>
        </div>
    </div>
</div>
